spring.datasource.url=jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}?serverTimezone=UTC
spring.datasource.username=${MYSQL_ADDON_USER}
spring.datasource.password=${MYSQL_ADDON_PASSWORD}

# Esto asegura que Spring no se cierre al arrancar
spring.main.web-application-type=servlet

server.port=${PORT:7860}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
maximum-pool-size=3

#Configuracion para vincular email:
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=pocketup.soporte@gmail.com
#spring.mail.password=owkrmbvhxdpznlon
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true




#spring.application.name=backend
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://btzvalddqbd3va47bj25-mysql.services.clever-cloud.com:3306/btzvalddqbd3va47bj25?serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/pocketup_db?useSSL=false&serverTimezone=UTC
#spring.datasource.username=ucpjoptfwqywxpub
#spring.datasource.password=aTW5mXXFduG1ARA1aVUq